version: "3"
services:
  app:
    container_name: app
    build: . #Dockerfile do node se encontra na pasta atual
    ports:
      - 5000:4005
    depends_on:
      - db # sรณ sobe quando o postgres tiver no ar
    volumes:
      - .:/app
  db:
    image: postgres:13
    container_name: db
    ports:
    - 2345:5432
    env_file:
      - .env #configurar POSTGRES_USER, POSTGRES_PASSWORD e POSTGRES_DB
    restart: always #container reinicia se morrer
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: